services:
  zdinnav:
    image: DOCKER_URL_VAR:VERSION_VAR
    container_name: zdinnav
    restart: unless-stopped
    ports:
      - "PORT_VAR:9200"
    networks:
      - zdinnavnet
    environment:
      - TZ=Asia/Shanghai 
    volumes:
      - CONFIG_PATH_VAR/configuration:/app/configuration
      - CONFIG_PATH_VAR/database:/app/database
      - CONFIG_PATH_VAR/logs:/app/Logs
networks:
  zdinnavnet:
      driver: bridge

volumes:
  fonts_volume:
